<?php

namespace Jovian\Venusian\AppKit\Input;

use Surface\Contracts\HumanInput\Key;

/**
 * macOS virtual key codes (Carbon `kVK_*`, ANSI positions) → Surface keys.
 * Layout independent; anything unmapped is Key::UNKNOWN.
 */
final class KeyCodeMap
{
    public static function key(int $key_code): Key
    {
        return match ($key_code) {
            0x00 => Key::A,
            0x01 => Key::S,
            0x02 => Key::D,
            0x03 => Key::F,
            0x04 => Key::H,
            0x05 => Key::G,
            0x06 => Key::Z,
            0x07 => Key::X,
            0x08 => Key::C,
            0x09 => Key::V,
            0x0B => Key::B,
            0x0C => Key::Q,
            0x0D => Key::W,
            0x0E => Key::E,
            0x0F => Key::R,
            0x10 => Key::Y,
            0x11 => Key::T,
            0x12 => Key::DIGIT_1,
            0x13 => Key::DIGIT_2,
            0x14 => Key::DIGIT_3,
            0x15 => Key::DIGIT_4,
            0x16 => Key::DIGIT_6,
            0x17 => Key::DIGIT_5,
            0x18 => Key::EQUALS,
            0x19 => Key::DIGIT_9,
            0x1A => Key::DIGIT_7,
            0x1B => Key::MINUS,
            0x1C => Key::DIGIT_8,
            0x1D => Key::DIGIT_0,
            0x1E => Key::RIGHT_BRACKET,
            0x1F => Key::O,
            0x20 => Key::U,
            0x21 => Key::LEFT_BRACKET,
            0x22 => Key::I,
            0x23 => Key::P,
            0x24 => Key::ENTER,
            0x25 => Key::L,
            0x26 => Key::J,
            0x27 => Key::APOSTROPHE,
            0x28 => Key::K,
            0x29 => Key::SEMICOLON,
            0x2A => Key::BACKSLASH,
            0x2B => Key::COMMA,
            0x2C => Key::SLASH,
            0x2D => Key::N,
            0x2E => Key::M,
            0x2F => Key::PERIOD,
            0x30 => Key::TAB,
            0x31 => Key::SPACE,
            0x32 => Key::GRAVE,
            0x33 => Key::BACKSPACE,
            0x35 => Key::ESCAPE,
            0x36 => Key::RIGHT_META,
            0x37 => Key::LEFT_META,
            0x38 => Key::LEFT_SHIFT,
            0x39 => Key::CAPS_LOCK,
            0x3A => Key::LEFT_ALT,
            0x3B => Key::LEFT_CTRL,
            0x3C => Key::RIGHT_SHIFT,
            0x3D => Key::RIGHT_ALT,
            0x3E => Key::RIGHT_CTRL,
            0x3F => Key::FUNCTION,
            0x41 => Key::NUMPAD_PERIOD,
            0x43 => Key::NUMPAD_MULTIPLY,
            0x45 => Key::NUMPAD_PLUS,
            0x47 => Key::CLEAR,
            0x4B => Key::NUMPAD_DIVIDE,
            0x4C => Key::NUMPAD_ENTER,
            0x4E => Key::NUMPAD_MINUS,
            0x51 => Key::NUMPAD_EQUALS,
            0x52 => Key::NUMPAD_0,
            0x53 => Key::NUMPAD_1,
            0x54 => Key::NUMPAD_2,
            0x55 => Key::NUMPAD_3,
            0x56 => Key::NUMPAD_4,
            0x57 => Key::NUMPAD_5,
            0x58 => Key::NUMPAD_6,
            0x59 => Key::NUMPAD_7,
            0x5B => Key::NUMPAD_8,
            0x5C => Key::NUMPAD_9,
            0x60 => Key::F5,
            0x61 => Key::F6,
            0x62 => Key::F7,
            0x63 => Key::F3,
            0x64 => Key::F8,
            0x65 => Key::F9,
            0x67 => Key::F11,
            0x6D => Key::F10,
            0x6E => Key::MENU,
            0x6F => Key::F12,
            0x72 => Key::INSERT,
            0x73 => Key::HOME,
            0x74 => Key::PAGE_UP,
            0x75 => Key::DELETE,
            0x76 => Key::F4,
            0x77 => Key::END,
            0x78 => Key::F2,
            0x79 => Key::PAGE_DOWN,
            0x7A => Key::F1,
            0x7B => Key::LEFT,
            0x7C => Key::RIGHT,
            0x7D => Key::DOWN,
            0x7E => Key::UP,
            default => Key::UNKNOWN,
        };
    }
}
